spring:
  application:
    name: greeting-service
greeting-service:
  greeting: "default"
  default-value: "default"
  
# Spring Boot Actuator  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
