spring:
  application:
    name: greeting-service
greeting-service:
  greeting: "dev"
  default-value: "dev"
  
# Spring Boot Actuator  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
